### ISSUE TITLE
mb-strtolower in activity.php

### ISSUE THREAD

**Issue by AZimmerhofer** [imath/bp-idea-stream#3]
Hello,

great plugin! Thanks for your work. We are using your plugin on a German website. So the word idea is being translated to Idee on this website. Links in the activity stream for comments or for new ideas are being posted, but the name of the link is lowercased - so the name of the link is idee and not Idee. You are using mb-strtolower on line 489 and on line 460. We deleted the php command and now the name of the link is not longer lowercased, Idee and not idee.

kind regards
Alex

**Comment by imath** [comment]
This is probably the wrong way to do it. Next time there will be an upgrade your edits will be lost.

I'll work on it to suggest you a better way ;)

**Comment by imath** [comment]
You can upgrade to 1.0.2 and then you'll be able to remove the lower case filters using this code in a `/wp-content/plugins/bp-custom.php` file:

```php
function bp_idea_stream_remove_format_filters() {
	remove_filter( 'bp_idea_stream_activity_admin_caption',       'bp_idea_stream_lower_case' );
	remove_filter( 'bp_idea_stream_activity_post_action_name',    'bp_idea_stream_lower_case' );
	remove_filter( 'bp_idea_stream_activity_comment_action_name', 'bp_idea_stream_lower_case' );
}
add_action( 'bp_init', 'bp_idea_stream_remove_format_filters', 6 );
```
