### ISSUE TITLE
php 8 error?

### ISSUE THREAD

**Issue by valuser** [imath/bp-idea-stream#5]
Came across this today.

just reporting an error  (have absolutely no coding knowledge/experience)

 PHP Deprecated:  Required parameter $user_id follows optional parameter $retval in /Users/mylocalsite/wp-content/plugins/bp-idea-stream-master/includes/activity.php on line 355

Was experimenting with php8.0.0 on a local site

Deactivating bp-idea-stream-master appears to allow the site return to normal with wp-idea-stream working normally.

Cheers & thanks

**Comment by imath** [comment]
Many thanks to your for reporting this issue, I'll fix it asap.
